version: '3.1'
networks:
  web:
  db:
services:
  nginx:
    image: nginx:1.17.10
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - web
  php:
    image: php:7.4-fpm
    container_name: php-fpm
    ports:
      - 9000:9000
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - web
      - db
  mysql:
    image: mysql:8.0.20
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: docker
    networks:
      - db

# - Post Install:
# - - Run:
# docker-compose exec php docker-php-ext-install pdo pdo_mysql
# docker-compose php restart